MONGO_URI = "mongodb+srv://kunalmandal1604_db_user:miyakhalifa10@album.uaktecw.mongodb.net/?appName=album"
CLOUDINARY_CLOUD_NAME = "dhb2sfajq"
CLOUDINARY_API_KEY = "554216984131877"
CLOUDINARY_API_SECRET = "LeS09uiohF6dKcW0Eet-yCiUJyM"
SMTP_EMAIL = "voidtech16@gmail.com"
SMTP_PASSWORD = "bxlc uocr czym jwji"
